# Generated by Django 4.2.1 on 2023-05-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заказчик')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, null=True, verbose_name='модель весов')),
                ('brand', models.CharField(default='Bizerba', max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Модель весов',
                'verbose_name_plural': 'Модели весов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(blank=True, max_length=128, verbose_name='сервисный инженер')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='работает')),
                ('to_remove', models.BooleanField(default=False, verbose_name='уволить')),
            ],
            options={
                'verbose_name': 'Инженер',
                'verbose_name_plural': 'Инженеры',
                'ordering': ['engineer'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='запчасть')),
                ('vendor_code', models.CharField(max_length=16, verbose_name='артикул')),
                ('quantity', models.IntegerField(default=0, verbose_name='остаток')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='описание')),
                ('scale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.scalemodel', verbose_name='Модель весов')),
            ],
            options={
                'verbose_name': 'ЗИП',
                'verbose_name_plural': 'ЗИП',
                'ordering': ['title', 'scale_id'],
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=16, null=True, unique=True, verbose_name='серийный номер')),
                ('scale_class', models.CharField(choices=[('3/6 кг', 'Кг 3 6'), ('6/15 кг', 'Кг 6 15'), ('15/30 кг', 'Кг 15 30'), ('30/60 кг', 'Кг 30 60'), ('60/150 кг', 'Кг 60 150'), ('600 кг', 'Кг 600'), ('1500 кг', 'Кг 1500')], max_length=32, null=True, verbose_name='класс весов')),
                ('platform', models.BooleanField(default=False, verbose_name='Платформа')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP-адрес')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='примечание')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer', verbose_name='заказчик')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.department', verbose_name='отдел')),
                ('scale_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.scalemodel', verbose_name='модель весов')),
            ],
            options={
                'verbose_name': 'Весы',
                'verbose_name_plural': 'Весы',
                'ordering': ['customer', 'department', 'scale_model'],
            },
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_num', models.CharField(max_length=16, null=True, verbose_name='Акт прихода')),
                ('date', models.DateField(null=True, verbose_name='Дата составления')),
                ('quantity', models.IntegerField(default=0, verbose_name='приход')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена, EUR')),
                ('description', models.CharField(default='пополнение', max_length=255, verbose_name='назначение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('to_remove', models.BooleanField(default=False, verbose_name='удалить')),
                ('vendor_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.sparepart', verbose_name='артикул')),
            ],
            options={
                'verbose_name': 'Поступление ЗИП',
                'verbose_name_plural': 'Поступление ЗИП',
                'ordering': ['act_num', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='LogReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='номер акта')),
                ('date', models.DateField(verbose_name='дата акта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('to_remove', models.BooleanField(default=False, verbose_name='удалить')),
                ('customer', models.ForeignKey(default='Бицерба РУС', null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer')),
            ],
            options={
                'verbose_name': 'Реестр прихода ЗИП',
                'verbose_name_plural': 'Реестр прихода ЗИП',
                'ordering': ['number', 'date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='заявка')),
                ('defect', models.TextField(blank=True, verbose_name='неисправность')),
                ('service_work', models.TextField(blank=True, verbose_name='выполненные работы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('to_remove', models.BooleanField(default=False, verbose_name='удалить')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer', verbose_name='заказчик')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.serviceengineer', verbose_name='сервисный инженер')),
                ('scale_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.scalemodel', verbose_name='модель весов')),
                ('serial_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.scale', verbose_name='серийный номер')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['number', 'customer', 'time_create'],
            },
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='установлено')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликован')),
                ('to_remove', models.BooleanField(default=False, verbose_name='удалить')),
                ('number_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.jobapplication', verbose_name='заявка')),
                ('spare_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.sparepart', verbose_name='ЗИП')),
            ],
            options={
                'verbose_name': 'Установка ЗИП',
                'verbose_name_plural': 'Установка ЗИП',
                'ordering': ['number_job', 'time_create'],
            },
        ),
    ]
